name: Build a JAR from book netwrok back-end
on:
  push:
    branches:
      - master



jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2



      - name: Set up JDK 17
        uses: actions/setup-java@v1



        with:
          java-version: '17'


      - name: Build with Maven
        run: mvn -f book-network/pom.xml clean install -DskipTests



      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3



        with:
          name: java-app
          path: 'book-network/target/*.jar'



      #- name: Run Tests
      # run: mvn test